apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: outbound-k8s-sensor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: outbound-k8s-sensor
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: outbound-k8s-sensor
  apiGroup: rbac.authorization.k8s.io